name: spreadsheets
description: A starting point for Dart libraries or applications.
version: 1.2.6
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  csv: ^5.1.1
  dotenv: ^4.2.0
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
